platform:ios,'7.0'
inhibit_all_warnings!
target ‘BianMin’ do
pod'AFNetworking','~>3.1.0'
pod 'SDWebImage', '~>3.7'
#pod 'UMengSocial', '~> 5.0'
pod 'UMengSocialCOM', '~> 5.2.1'
pod 'MJRefresh'
pod 'LXMButtonImagePosition', '~> 1.1.1'
pod 'LBXScan','~> 1.1.1'
pod 'IQKeyboardManager'
pod 'Bugly'
end
